# Generated by Django 5.2.3 on 2025-06-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('person_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asin', models.CharField(blank=True, max_length=20, null=True)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trackings', models.TextField(blank=True, null=True)),
                ('shipped', models.BooleanField(default=False)),
            ],
        ),
    ]
